"""refactor_models_add_personal_bests

Revision ID: 0c358ff7afec
Revises: 392772091020
Create Date: 2026-04-20 11:35:05.166264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0c358ff7afec"
down_revision: Union[str, Sequence[str], None] = "392772091020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_bests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("stroke", sa.String(length=20), nullable=False),
        sa.Column("time_seconds", sa.Float(), nullable=False),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"], ["athlete_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_bests_athlete_id"),
        "personal_bests",
        ["athlete_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_bests_id"), "personal_bests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_personal_bests_stroke"), "personal_bests", ["stroke"], unique=False
    )
    op.drop_constraint(
        op.f("athlete_profiles_user_id_key"), "athlete_profiles", type_="unique"
    )
    op.create_index(
        op.f("ix_athlete_profiles_branch_id"),
        "athlete_profiles",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_athlete_profiles_coach_id"),
        "athlete_profiles",
        ["coach_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_athlete_profiles_gender"), "athlete_profiles", ["gender"], unique=False
    )
    op.create_index(
        op.f("ix_athlete_profiles_school_id"),
        "athlete_profiles",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_athlete_profiles_user_id"),
        "athlete_profiles",
        ["user_id"],
        unique=True,
    )
    op.drop_column("athlete_profiles", "personal_best_50m_freestyle")
    op.drop_column("athlete_profiles", "personal_best_200m_freestyle")
    op.drop_column("athlete_profiles", "personal_best_100m_freestyle")
    op.drop_column("athlete_profiles", "personal_best_200m_breaststroke")
    op.drop_column("athlete_profiles", "personal_best_100m_breaststroke")
    op.drop_column("athlete_profiles", "personal_best_50m_breaststroke")
    op.create_index(
        op.f("ix_branches_school_id"), "branches", ["school_id"], unique=False
    )
    op.drop_constraint(
        op.f("coach_profiles_user_id_key"), "coach_profiles", type_="unique"
    )
    op.create_index(
        op.f("ix_coach_profiles_branch_id"),
        "coach_profiles",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coach_profiles_school_id"),
        "coach_profiles",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coach_profiles_user_id"), "coach_profiles", ["user_id"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_schools_city"), "schools", ["city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schools_city"), table_name="schools")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_coach_profiles_user_id"), table_name="coach_profiles")
    op.drop_index(op.f("ix_coach_profiles_school_id"), table_name="coach_profiles")
    op.drop_index(op.f("ix_coach_profiles_branch_id"), table_name="coach_profiles")
    op.create_unique_constraint(
        op.f("coach_profiles_user_id_key"),
        "coach_profiles",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_branches_school_id"), table_name="branches")
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_50m_breaststroke",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_100m_breaststroke",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_200m_breaststroke",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_100m_freestyle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_200m_freestyle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "athlete_profiles",
        sa.Column(
            "personal_best_50m_freestyle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_athlete_profiles_user_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_school_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_gender"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_coach_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_branch_id"), table_name="athlete_profiles")
    op.create_unique_constraint(
        op.f("athlete_profiles_user_id_key"),
        "athlete_profiles",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_personal_bests_stroke"), table_name="personal_bests")
    op.drop_index(op.f("ix_personal_bests_id"), table_name="personal_bests")
    op.drop_index(op.f("ix_personal_bests_athlete_id"), table_name="personal_bests")
    op.drop_table("personal_bests")
    # ### end Alembic commands ###
