"""add_heats_and_heat_entries

Revision ID: 5dc24e29defb
Revises: 9a9648788ef1
Create Date: 2026-04-20 15:56:13.983242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5dc24e29defb"
down_revision: Union[str, Sequence[str], None] = "9a9648788ef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("swim_event_id", sa.Integer(), nullable=False),
        sa.Column("heat_number", sa.Integer(), nullable=False),
        sa.Column("lane_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["swim_event_id"], ["swim_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_heats_id"), "heats", ["id"], unique=False)
    op.create_index(
        op.f("ix_heats_swim_event_id"), "heats", ["swim_event_id"], unique=False
    )
    op.create_table(
        "heat_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("heat_id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("lane", sa.Integer(), nullable=False),
        sa.Column("result_time", sa.Float(), nullable=True),
        sa.Column("place", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["heat_id"], ["heats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_heat_entries_entry_id"), "heat_entries", ["entry_id"], unique=True
    )
    op.create_index(
        op.f("ix_heat_entries_heat_id"), "heat_entries", ["heat_id"], unique=False
    )
    op.create_index(op.f("ix_heat_entries_id"), "heat_entries", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_heat_entries_id"), table_name="heat_entries")
    op.drop_index(op.f("ix_heat_entries_heat_id"), table_name="heat_entries")
    op.drop_index(op.f("ix_heat_entries_entry_id"), table_name="heat_entries")
    op.drop_table("heat_entries")
    op.drop_index(op.f("ix_heats_swim_event_id"), table_name="heats")
    op.drop_index(op.f("ix_heats_id"), table_name="heats")
    op.drop_table("heats")
    # ### end Alembic commands ###
