"""add_competition_model

Revision ID: 637ea40d516d
Revises: daaedb375a75
Create Date: 2026-04-20 11:53:21.124119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "637ea40d516d"
down_revision: Union[str, Sequence[str], None] = "daaedb375a75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competitions_city"), "competitions", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_created_by"), "competitions", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_competitions_id"), "competitions", ["id"], unique=False)
    op.create_index(
        op.f("ix_competitions_name"), "competitions", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_start_date"), "competitions", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_status"), "competitions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_competitions_status"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_start_date"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_name"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_id"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_created_by"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_city"), table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
