"""add_swim_events

Revision ID: 83ce2701a59c
Revises: b1e0dd3e7e57
Create Date: 2026-04-20 12:35:28.126446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "83ce2701a59c"
down_revision: Union[str, Sequence[str], None] = "b1e0dd3e7e57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swim_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("stroke", sa.String(length=30), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("is_relay", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_swim_events_competition_id"),
        "swim_events",
        ["competition_id"],
        unique=False,
    )
    op.create_index(op.f("ix_swim_events_id"), "swim_events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swim_events_id"), table_name="swim_events")
    op.drop_index(op.f("ix_swim_events_competition_id"), table_name="swim_events")
    op.drop_table("swim_events")
    # ### end Alembic commands ###
