"""add_entries_table

Revision ID: 9a9648788ef1
Revises: 83ce2701a59c
Create Date: 2026-04-20 15:24:23.734801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a9648788ef1"
down_revision: Union[str, Sequence[str], None] = "83ce2701a59c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("swim_event_id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entry_time", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"], ["athlete_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competitions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["swim_event_id"], ["swim_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entries_athlete_id"), "entries", ["athlete_id"], unique=False
    )
    op.create_index(
        op.f("ix_entries_competition_id"), "entries", ["competition_id"], unique=False
    )
    op.create_index(op.f("ix_entries_id"), "entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_entries_swim_event_id"), "entries", ["swim_event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entries_swim_event_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_competition_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_athlete_id"), table_name="entries")
    op.drop_table("entries")
    # ### end Alembic commands ###
