"""add_age_categories

Revision ID: b1e0dd3e7e57
Revises: 637ea40d516d
Create Date: 2026-04-20 12:27:37.345731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b1e0dd3e7e57"
down_revision: Union[str, Sequence[str], None] = "637ea40d516d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "age_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_age_categories_competition_id"),
        "age_categories",
        ["competition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_age_categories_id"), "age_categories", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_age_categories_id"), table_name="age_categories")
    op.drop_index(op.f("ix_age_categories_competition_id"), table_name="age_categories")
    op.drop_table("age_categories")
    # ### end Alembic commands ###
