"""add_schools_profiles_personal_bests

Revision ID: daaedb375a75
Revises: 7cc05bcd9a93
Create Date: 2026-04-20 11:41:48.195192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "daaedb375a75"
down_revision: Union[str, Sequence[str], None] = "7cc05bcd9a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
