"""add_school_fields_and_coach_photo

Revision ID: f8f612fc54d0
Revises: e70a0b520b7a
Create Date: 2026-04-21 12:54:02.639751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f8f612fc54d0"
down_revision: Union[str, Sequence[str], None] = "e70a0b520b7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coach_profiles", sa.Column("photo_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "coach_profiles", sa.Column("bio", sa.String(length=1000), nullable=True)
    )
    op.add_column(
        "coach_profiles",
        sa.Column("birth_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "coach_profiles",
        sa.Column("achievements", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "schools", sa.Column("description", sa.String(length=2000), nullable=True)
    )
    op.add_column(
        "schools", sa.Column("logo_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "schools", sa.Column("cover_url", sa.String(length=500), nullable=True)
    )
    op.add_column("schools", sa.Column("founded_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "founded_year")
    op.drop_column("schools", "cover_url")
    op.drop_column("schools", "logo_url")
    op.drop_column("schools", "description")
    op.drop_column("coach_profiles", "achievements")
    op.drop_column("coach_profiles", "birth_date")
    op.drop_column("coach_profiles", "bio")
    op.drop_column("coach_profiles", "photo_url")
    # ### end Alembic commands ###
